### ISSUE TITLE
VPC reading error

### ISSUE THREAD

**Issue by soufi** [mulesoft-consulting/terraform-provider-anypoint#29]
Just noticed a bug when reading the firewall rules after VPC creation. 

Here's the stack trace 

```
Stack trace from the terraform-provider-anypoint plugin:

panic: interface conversion: interface {} is int, not int32

goroutine 130 [running]:
github.com/mulesoft-consulting/terraform-provider-anypoint/anypoint.newVPCBody(0x19207a8)
	/Users/sboulealf/go/src/github.com/mulesoft-consulting/terraform-provider-anypoint/anypoint/resource_vpc.go:320 +0xcd4
github.com/mulesoft-consulting/terraform-provider-anypoint/anypoint.resourceVPCCreate({0x19207a8, 0xc0000f4b40}, 0xc0002f17b8, {0x17f6340, 0xc0001f8930})
	/Users/sboulealf/go/src/github.com/mulesoft-consulting/terraform-provider-anypoint/anypoint/resource_vpc.go:138 +0x18b
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).create(0xc0001ae240, {0x1920738, 0xc000239b40}, 0x2, {0x17f6340, 0xc0001f8930})
	/Users/sboulealf/go/pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.4.4/helper/schema/resource.go:285 +0x1a3
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc0001ae240, {0x1920738, 0xc000239b40}, 0xc0001f8bd0, 0xc00007c100, {0x17f6340, 0xc0001f8930})
	/Users/sboulealf/go/pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.4.4/helper/schema/resource.go:396 +0x86f
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0xc0001960a8, {0x1920738, 0xc000239b40}, 0xc000116370)
	/Users/sboulealf/go/pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.4.4/helper/schema/grpc_provider.go:955 +0x9aa
github.com/hashicorp/terraform-plugin-go/tfprotov5/server.(*server).ApplyResourceChange(0xc000191340, {0x19207e0, 0xc000726180}, 0xc00040a1a0)
	/Users/sboulealf/go/pkg/mod/github.com/hashicorp/terraform-plugin-go@v0.2.1/tfprotov5/server/server.go:332 +0x6c
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler({0x17e6f80, 0xc000191340}, {0x19207e0, 0xc000726180}, 0xc00022a240, 0x0)
	/Users/sboulealf/go/pkg/mod/github.com/hashicorp/terraform-plugin-go@v0.2.1/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:380 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0001ac540, {0x192e090, 0xc000164000}, 0xc00072e000, 0xc000465650, 0x1e47d80, 0x0)
	/Users/sboulealf/go/pkg/mod/google.golang.org/grpc@v1.32.0/server.go:1194 +0xc8f
google.golang.org/grpc.(*Server).handleStream(0xc0001ac540, {0x192e090, 0xc000164000}, 0xc00072e000, 0x0)
	/Users/sboulealf/go/pkg/mod/google.golang.org/grpc@v1.32.0/server.go:1517 +0xa2a
google.golang.org/grpc.(*Server).serveStreams.func1.2()
	/Users/sboulealf/go/pkg/mod/google.golang.org/grpc@v1.32.0/server.go:859 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
	/Users/sboulealf/go/pkg/mod/google.golang.org/grpc@v1.32.0/server.go:857 +0x294

Error: The terraform-provider-anypoint plugin crashed!

```

**Comment by soufi** [comment]
this was resolved and is now part of the `v1.1.0`
